name: Run tests and upload coverage to Codecov
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Create and start emulator
        run: |
          echo "y" | sdkmanager "system-images;android-30;default;x86"
          echo "no" | avdmanager create avd --force --name testEmulator --abi default/x86 --package "system-images;android-30;default;x86"
          $ANDROID_HOME/emulator/emulator -avd testEmulator -no-audio -no-window &
          $ANDROID_HOME/platform-tools/adb wait-for-device
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate Jacoco Test Report
        run: ./gradlew jacocoTestReport
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: aoeai/aoeai-qigua-android
